import type { MockData } from "./types"

export const mockData: MockData = {
  profile: {
    id: "profile-1",
    name: "Aaditya Kumar",
    avatar: "/images/profile-photo.png",
    status: "Available for work",
    bio: "I design intuitive, elegant digital experiences that solve real problems. UI/UX is not just my job, it's my craft. ✨",
    email: "aaditya@example.com",
    phone: "+1 (555) 123-4567",
    location: "Mohali, India",
  },
  skills: ["User Research", "Wireframing", "HTML", "Visual Design", "Product Design", "User Flow", "Prototyping"],
  education: [
    {
      id: "edu-1",
      degree: "B.Tech (Computer Science)",
      institution: "Chandigarh Group Singh University, Mohali",
      period: "2022 - 2026",
      startDate: "2022-08-01",
      endDate: "2026-05-31",
      description: "Focused on software engineering, data structures, and UI/UX design principles.",
      gpa: "8.5/10",
    },
    {
      id: "edu-2",
      degree: "Diploma in CSE",
      institution: "XYZ College, Mohali",
      period: "2019 - 2022",
      startDate: "2019-08-01",
      endDate: "2022-05-31",
      description: "Foundation in computer science and programming fundamentals.",
      gpa: "9.2/10",
    },
  ],
  technologies: ["Miro", "Figma", "XD", "Sketch", "Principle"],
  experience: [
    {
      id: "exp-1",
      role: "Senior UX Designer",
      company: "Google",
      period: "2022 - Present",
      startDate: "2022-06-01",
      endDate: "",
      isCurrentRole: true,
      description:
        "Leading design initiatives for Google Workspace, focusing on user experience optimization and accessibility improvements.",
      location: "Mountain View, CA",
    },
    {
      id: "exp-2",
      role: "UX Researcher",
      company: "Adobe",
      period: "2019 - 2022",
      startDate: "2019-07-01",
      endDate: "2022-05-31",
      description: "Conducted user research studies and usability testing for Creative Cloud applications.",
      location: "San Jose, CA",
    },
  ],
  certifications: [
    {
      id: "cert-1",
      title: "Google UX Design Professional Certificate",
      issuer: "Google",
      status: "Certificate earned",
      earned: true,
      dateEarned: "2021-12-15",
      credentialId: "GUX-2021-12345",
      url: "https://coursera.org/verify/professional-cert/abc123",
    },
    {
      id: "cert-2",
      title: "Udemy UX Design Course",
      issuer: "Udemy",
      status: "Certificate not earned",
      earned: false,
    },
  ],
  projects: [
    {
      id: "proj-1",
      title: "Eventsify - Ultimate Template",
      image: "/placeholder.svg?height=240&width=320",
      description: "A comprehensive event management platform with modern UI/UX design and seamless user experience.",
      technologies: ["React", "Node.js", "MongoDB", "Figma"],
      url: "https://eventsify.example.com",
      githubUrl: "https://github.com/aaditya/eventsify",
      startDate: "2023-01-01",
      endDate: "2023-06-30",
      status: "completed",
    },
    {
      id: "proj-2",
      title: "Techzo Digital Agency Web Design",
      image: "/placeholder.svg?height=240&width=320",
      description:
        "Modern, responsive website design for a digital marketing agency with focus on conversion optimization.",
      technologies: ["Next.js", "Tailwind CSS", "Framer Motion"],
      url: "https://techzo.example.com",
      startDate: "2023-07-01",
      endDate: "",
      status: "in-progress",
    },
  ],
  socials: [
    {
      id: "social-1",
      platform: "Instagram",
      handle: "@aaditya_ui",
      icon: "Instagram",
      url: "https://instagram.com/aaditya_ui",
    },
    {
      id: "social-2",
      platform: "LinkedIn",
      handle: "@aaditya_ui",
      icon: "Linkedin",
      url: "https://linkedin.com/in/aaditya_ui",
    },
    {
      id: "social-3",
      platform: "Behance",
      handle: "@aaditya_ui",
      icon: "Palette",
      url: "https://behance.net/aaditya_ui",
    },
    {
      id: "social-4",
      platform: "YouTube",
      handle: "@aaditya_ui",
      icon: "Youtube",
      url: "https://youtube.com/@aaditya_ui",
    },
    {
      id: "social-5",
      platform: "Twitter",
      handle: "@aaditya_ui",
      icon: "Twitter",
      url: "https://twitter.com/aaditya_ui",
    },
    {
      id: "social-6",
      platform: "Dribbble",
      handle: "@aaditya_ui",
      icon: "Circle",
      url: "https://dribbble.com/aaditya_ui",
    },
  ],
}
